name: Publish CI

on:
  push:
    branches: ["zero"]
  pull_request:
    branches: ["zero"]

env:
  NODE_VERSION: "22.x"
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  REGISTRY: "https://registry.npmjs.org"
  SCOPE: "@z-code"
  # USER: ${{ github.actor }}
  # PASS: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY }}
          scope: ${{ env.SCOPE }}
      - run: |
          corepack enable
          yarn install
      - run: yarn build
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
